name: deep
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pytorch
  - tqdm
  - optuna
  - statsmodels
  - scikit-learn
  - numba
  - reformer-pytorch