seed = 42
device = cuda
path = Datasets/TSB-AD-U/
file_list = Datasets/File_List/TSB-AD-U-Tuning.csv

batch_size = 1024
lr = 0.01
epochs = 20
win_size = 32
validation_size = 0.2

metrics = restr
strategy = overlapping
