[general]
seed = 1
path = Datasets/TSB-AD-U/
file_list = Datasets/File_List/TSB-AD-U-Eva-Full.csv

[model]
win_size = 32


[trainer]
batch_size = 1024
lr = 0.01
device = cuda
validation_size = 0.2
epochs = 20

[evaluator]
batch_size = 1024
device = cuda
metrics = restr
strategy = overlapping
