[experiment]
seed = 42
device = cuda
path = Datasets/TSB-AD-U/
file_list = Datasets/File_List/TSB-AD-U-Eva-Full.csv

batch_size = 1024
lr = 0.01
epochs = 20
win_size = 32
validation_size = 0.2

metrics = restr
strategy = overlapping
stride = 1

output_dir = results/TimesNet
output_name = ws{ws}_seed{seed}.csv

[model]
model_name = TimesNet
task_name = anomaly_detection
pred_len = 0
top_k = 3
d_model = 8
d_ff = 16
num_kernels = 6
e_layers = 1
embed = timeF
freq = t
dropout = 0.1
enc_in = 1
c_out = 1