model_name=TimeMixer
task_name=anomaly_detection
pred_len=0   
d_model=8
d_ff=16   
factor=3    
e_layers=1    
d_layers=1
enc_in=1      
dec_in=1     
c_out=1      
n_heads=2
activation='gelu'
moving_avg=25
embed="fixed"  
freq='t'       
dropout=0.1   
down_sampling_window=3
channel_independence=True
decomp_method='moving_avg'
down_sampling_layers=2
use_norm=False
down_sampling_method="avg"